### PR TITLE
Detect "host" correctly and create regex groupindex properly.

### PR DESCRIPTION
**Pull request by cjeanneret**
This solves #132

### CODE REVIEW

**Comment by mattab** [comment]
Thanks for the PR @cjeanneret 
could you please paste here an example log file (eg 3-4 lines) that was not imported correctly for you?

**Comment by cjeanneret** [comment]
Hello,

For example:
```
2016-02-19      08:47:30        LHR3    602     193.5.216.100   GET
<host/url>     403     <host/url>  -       -       Error
QiQWoa19c_jImMTmlHfS81WnnlHKsPr5Tz1jqTlYe540PqvWwaoPLA==        <host>
  https   721     0.000   -       TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256
  Error
2016-02-19      08:47:30        LHR3    602     193.5.216.100   GET
<host/url>     403     <host/url>   -       -       Error
7zOo738xvSMEfChgxTT1kbP1lXAvChcz9zzXp2gQmpgaNJ-YleZcgg==        <host>
  https   721     0.001   -       TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256
  Error
2016-02-19      08:47:31        LHR3    602     193.5.216.100   GET
<host/url>     403     <host/url>    -       -       Error
426LSYv6x61VyK2VS_jCnNOC-GpP-Eo5MR2j6CrSwkPTjZ7gUXN-Zw==        <host>
  https   721     0.002   -       TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256
  Error
```

I'm not really able to (publicly) provide the full URLs, as it's a dev
website not yet published.

Nevertheless, all hosts and uri are well-formated, and, funnily, the
test actually does work. It's just when I try to push those logs to
piwik that it crashes, asking for the site ID…

**Comment by cjeanneret** [comment]
Hello,

For example:
```
2016-02-19      08:47:30        LHR3    602     193.5.216.100   GET     <host/url>     403     <host/url>  -       -       Error   QiQWoa19c_jImMTmlHfS81WnnlHKsPr5Tz1jqTlYe540PqvWwaoPLA==        <host>    https   721     0.000   -       TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256     Error
2016-02-19      08:47:30        LHR3    602     193.5.216.100   GET     <host/url>     403     <host/url>   -       -       Error   7zOo738xvSMEfChgxTT1kbP1lXAvChcz9zzXp2gQmpgaNJ-YleZcgg==        <host>    https   721     0.001   -       TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256     Error
2016-02-19      08:47:31        LHR3    602     193.5.216.100   GET     <host/url>     403     <host/url>    -       -       Error   426LSYv6x61VyK2VS_jCnNOC-GpP-Eo5MR2j6CrSwkPTjZ7gUXN-Zw==        <host>    https   721     0.002   -       TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256     Error
```

I'm not really able to (publicly) provide the full URLs, as it's a dev website not yet published.

Nevertheless, all hosts and uri are well-formated, and, funnily, the test actually does work. It's just when I try to push those logs to piwik that it crashes, asking for the site ID…

**Comment by cjeanneret** [comment]
Hello,

Any news regarding this pull-request?

Cheers,

C.

**Comment by mattab** [comment]
@cjeanneret do you mind posting the log line including the first few lines with the list of column names? What is `x-host-header` set to, in your logs? 

here is our current automated test cases:
 * https://github.com/piwik/piwik-log-analytics/blob/master/tests/logs/amazon_cloudfront_web.log
 * https://github.com/piwik/piwik-log-analytics/blob/master/tests/logs/amazon_cloudfront_rtmp.log

they both have `x-host-header` set to such value: `random_string.cloudfront.net` 

So maybe a more correct solution would be to use x-host-header if it is set, and if not use `x-host`?

**Comment by mattab** [comment]
Still thinking this PR is not finished yet, as suggested:  maybe a more correct solution would be to use x-host-header if it is set, and if not use x-host?

ping @jroberts235 @cjeanneret  would be great if you can post a log file with the first line showing the field names

**Comment by mattab** [comment]
Still waiting for feedback from  @jroberts235 @cjeanneret  
Thanks

**Comment by sgiehl** [comment]
Closing this one, as the source repo does not exist anymore.

**Comment by mattab** [comment]
fyi @sgiehl the same PR was created by someone else in https://github.com/matomo-org/matomo-log-analytics/pull/283 so added that one to current sprint as it seems useful

**Pull request closed without merging**
