### PR TITLE
Add haproxy log format

### PR DESCRIPTION
**Pull request by fdellwing**
See https://forum.matomo.org/t/regex-fuer-haproxy/29959 for some background (in german).

### CODE REVIEW

**Comment by fdellwing** [comment]
It was not easy to get `nose` installed, but now it should be good to merge.

**Comment by Findus23** [comment]
@fdellwing That's why it is planned to switch to python3 and also use a modern test system instead.
https://github.com/matomo-org/matomo-log-analytics/pull/205

**Comment by fdellwing** [comment]
I don't know why the autodetection does not work, is it important that it works?

**Comment by fdellwing** [comment]
Any progress on this?

**Comment by JackSlateur** [comment]
The following regexp match on my logs (haproxy httplog):
`'(?P<ip>[\w*.]+).*\[(?P<date>.*)\].*\ (?P<status>\\b\d{3}\\b)\ (?P<length>\d+)\ -.*\"(?P<method>\S+)\ (?P<path>\S+).*'`

**Pull request merged**
