### PR TITLE
Update shebang to stick to Python version 2

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by sgiehl** [comment]
I think this would break #195

**Comment by J0WI** [comment]
It doesn't break #195, but it will select Python 2 automatically, if installed. #195 is only thrown if you try to force Python 3.

**Comment by dbrgn** [comment]
#242 is probably the better solution. Only 3 months left until Python 2 is officially unsupported: https://pythonclock.org/

**Comment by sgiehl** [comment]
Closing this in favor of #242

**Pull request closed without merging**
